inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - standard-custom
  - rubocop-performance

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml

inherit_from:
  - .rubocop/rails.yml
  - .rubocop/rspec.yml
  - .rubocop/custom.yml
  - .rubocop_todo.yml
  - .rubocop/strict.yml

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.2
